### ISSUE TITLE
Location checklist

### ISSUE THREAD

**Issue by Mirv** [Mirv/pet_shop#15]
- [ ] nix id visually
- [ ] pets count first?
- [ ] add enum field
- [ ] set enum validation never blank & default inactive
- [ ] enum status translated to string 
- [ ] show section of location probably needs edit if owner
- [ ] show section of location list of pets: pet name / type & link to it
- [ ] show section of location list of pets: remove pet location from
